[debug] [2023-01-15T14:33:04.956Z] ----------------------------------------------------------------------
[debug] [2023-01-15T14:33:04.958Z] Command:       C:\Program Files\nodejs\node.exe C:\Users\jotac\AppData\Roaming\npm\node_modules\firebase-tools\lib\bin\firebase.js deploy
[debug] [2023-01-15T14:33:04.958Z] CLI Version:   10.9.2
[debug] [2023-01-15T14:33:04.958Z] Platform:      win32
[debug] [2023-01-15T14:33:04.958Z] Node Version:  v18.12.1
[debug] [2023-01-15T14:33:04.959Z] Time:          Sun Jan 15 2023 11:33:04 GMT-0300 (Horário Padrão de Brasília)
[debug] [2023-01-15T14:33:04.960Z] ----------------------------------------------------------------------
[debug] 
[debug] [2023-01-15T14:33:05.026Z] > command requires scopes: ["email","openid","https://www.googleapis.com/auth/cloudplatformprojects.readonly","https://www.googleapis.com/auth/firebase","https://www.googleapis.com/auth/cloud-platform"]
[debug] [2023-01-15T14:33:05.027Z] > authorizing via signed-in user (jotanaval2009@gmail.com)
[debug] [2023-01-15T14:33:05.027Z] [iam] checking project gestao-excelencia-34e46 for permissions ["firebase.projects.get","firebasehosting.sites.update"]
[debug] [2023-01-15T14:33:05.029Z] >>> [apiv2][query] POST https://cloudresourcemanager.googleapis.com/v1/projects/gestao-excelencia-34e46:testIamPermissions [none]
[debug] [2023-01-15T14:33:05.029Z] >>> [apiv2][body] POST https://cloudresourcemanager.googleapis.com/v1/projects/gestao-excelencia-34e46:testIamPermissions {"permissions":["firebase.projects.get","firebasehosting.sites.update"]}
[debug] [2023-01-15T14:33:26.138Z] [iam] error while checking permissions, command may fail: FirebaseError: Failed to make request to https://cloudresourcemanager.googleapis.com/v1/projects/gestao-excelencia-34e46:testIamPermissions
[debug] [2023-01-15T14:33:26.143Z] >>> [apiv2][query] GET https://firebase.googleapis.com/v1beta1/projects/gestao-excelencia-34e46 [none]
[debug] [2023-01-15T14:33:48.262Z] Failed to make request to https://firebase.googleapis.com/v1beta1/projects/gestao-excelencia-34e46
[debug] [2023-01-15T14:34:10.386Z] FirebaseError: Failed to make request to https://firebase.googleapis.com/v1beta1/projects/gestao-excelencia-34e46
    at RetryOperation._fn (C:\Users\jotac\AppData\Roaming\npm\node_modules\firebase-tools\lib\apiv2.js:240:31)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
[error] 
[error] Error: Failed to get Firebase project gestao-excelencia-34e46. Please make sure the project exists and your account has permission to access it.
[debug] [2023-01-15T14:35:11.351Z] ----------------------------------------------------------------------
[debug] [2023-01-15T14:35:11.353Z] Command:       C:\Program Files\nodejs\node.exe C:\Users\jotac\AppData\Roaming\npm\node_modules\firebase-tools\lib\bin\firebase.js deploy
[debug] [2023-01-15T14:35:11.354Z] CLI Version:   11.20.0
[debug] [2023-01-15T14:35:11.354Z] Platform:      win32
[debug] [2023-01-15T14:35:11.354Z] Node Version:  v18.12.1
[debug] [2023-01-15T14:35:11.355Z] Time:          Sun Jan 15 2023 11:35:11 GMT-0300 (Horário Padrão de Brasília)
[debug] [2023-01-15T14:35:11.356Z] ----------------------------------------------------------------------
[debug] 
[debug] [2023-01-15T14:35:11.436Z] > command requires scopes: ["email","openid","https://www.googleapis.com/auth/cloudplatformprojects.readonly","https://www.googleapis.com/auth/firebase","https://www.googleapis.com/auth/cloud-platform"]
[debug] [2023-01-15T14:35:11.437Z] > authorizing via signed-in user (jotanaval2009@gmail.com)
[debug] [2023-01-15T14:35:11.437Z] [iam] checking project gestao-excelencia-34e46 for permissions ["firebase.projects.get","firebasehosting.sites.update"]
[debug] [2023-01-15T14:35:11.440Z] >>> [apiv2][query] POST https://cloudresourcemanager.googleapis.com/v1/projects/gestao-excelencia-34e46:testIamPermissions [none]
[debug] [2023-01-15T14:35:11.440Z] >>> [apiv2][(partial)header] POST https://cloudresourcemanager.googleapis.com/v1/projects/gestao-excelencia-34e46:testIamPermissions x-goog-quota-user=projects/gestao-excelencia-34e46
[debug] [2023-01-15T14:35:11.441Z] >>> [apiv2][body] POST https://cloudresourcemanager.googleapis.com/v1/projects/gestao-excelencia-34e46:testIamPermissions {"permissions":["firebase.projects.get","firebasehosting.sites.update"]}
[debug] [2023-01-15T14:35:32.526Z] [iam] error while checking permissions, command may fail: FirebaseError: Failed to make request to https://cloudresourcemanager.googleapis.com/v1/projects/gestao-excelencia-34e46:testIamPermissions
[debug] [2023-01-15T14:35:32.530Z] >>> [apiv2][query] GET https://firebase.googleapis.com/v1beta1/projects/gestao-excelencia-34e46 [none]
[debug] [2023-01-15T14:35:53.578Z] Failed to make request to https://firebase.googleapis.com/v1beta1/projects/gestao-excelencia-34e46
[debug] [2023-01-15T14:35:58.607Z] Error: Timed out.
    at Timeout._onTimeout (C:\Users\jotac\AppData\Roaming\npm\node_modules\firebase-tools\lib\utils.js:253:49)
    at listOnTimeout (node:internal/timers:564:17)
    at process.processTimers (node:internal/timers:507:7)
[error] 
[error] Error: An unexpected error has occurred.
[debug] [2023-01-15T14:36:24.263Z] ----------------------------------------------------------------------
[debug] [2023-01-15T14:36:24.265Z] Command:       C:\Program Files\nodejs\node.exe C:\Users\jotac\AppData\Roaming\npm\node_modules\firebase-tools\lib\bin\firebase.js login
[debug] [2023-01-15T14:36:24.266Z] CLI Version:   11.20.0
[debug] [2023-01-15T14:36:24.266Z] Platform:      win32
[debug] [2023-01-15T14:36:24.266Z] Node Version:  v18.12.1
[debug] [2023-01-15T14:36:24.267Z] Time:          Sun Jan 15 2023 11:36:24 GMT-0300 (Horário Padrão de Brasília)
[debug] [2023-01-15T14:36:24.267Z] ----------------------------------------------------------------------
[debug] 
[info] Already logged in as jotanaval2009@gmail.com
[debug] [2023-01-15T14:36:34.424Z] Error: Timed out.
    at Timeout._onTimeout (C:\Users\jotac\AppData\Roaming\npm\node_modules\firebase-tools\lib\utils.js:253:49)
    at listOnTimeout (node:internal/timers:564:17)
    at process.processTimers (node:internal/timers:507:7)
[error] 
[error] Error: An unexpected error has occurred.
